{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "79bbd7e3-a692-4d82-aa9f-75145233df02",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "from Mars:\n",
      "{'distance to earth': 125000000}\n",
      "from Mercury:\n",
      "{'distance to earth': 89000000}\n",
      "{'A year on this planet lasts': 90.46047267140838}\n",
      "from Jupiter:\n",
      "{'distance to earth': 632000000}\n",
      "{'A year on this planet lasts': 4452.69603478531}\n"
     ]
    }
   ],
   "source": [
    "#Note: please enter distance_from_sun assuming it will be changed to millions of kilometers e.g. 147\n",
    "## CODING CHALLENGE\n",
    "# 25 MARKS\n",
    "\"\"\"\n",
    "A] Design a parent class called Planet\n",
    "\n",
    "It must have:\n",
    "- General attributes: name, distance_from_sun, planet_type\n",
    "- A get_distance_to_earth() method that gives you the absolute distance from the Earth.\n",
    "\n",
    "!!! You can take the distance from the Sun to the Earth as 147 million kilometres !!!\n",
    "\n",
    "For example, if the planet’s distance_from_sun was 148 million kilometres when you call the get_distance_from_earth()\n",
    "method, it should give us the distance like this: {'distance to earth’': 1000000} where the implied unit is kilometres.\n",
    "This means that the planet is 1 million kilometres away from Earth.\n",
    "\n",
    "   > This question uses an oversimplification of the solar system model, not taking into account orbit position or the\n",
    "    eccentricity of the orbit, so in reality the result will be an approximate value with a reasonable margin of error.\n",
    "\"\"\"\n",
    "import math\n",
    "class Planet:\n",
    "    def __init__(self, name, distance_from_sun, planet_type):\n",
    "        self.name = name\n",
    "        self.distance_from_sun = distance_from_sun \n",
    "        self.planet_type = planet_type \n",
    "\n",
    "    def get_distance_to_earth(self):\n",
    "        # distance_to_earth is the distance_from_sun minus 147 million kilometers (distance between earth and the sun)\n",
    "        # int and abs used to ensure the result is a positive integer, which is returned with the implied unit of km\n",
    "        self.distance_to_earth = abs(self.distance_from_sun - 147)\n",
    "        return {'distance to earth': self.distance_to_earth * 1000000}\n",
    "\n",
    "\n",
    "\"\"\"\n",
    "B] Design a child class called Mercury, which inherits from the Planet class.\n",
    "This class should have exactly the same attributes as its parent class,\n",
    "Your child class should also have a static method called happy_new_year(), which\n",
    "would give us the information on how long a year lasts on the planet (in whatever way you wish!). \n",
    "You can take Earth Days as the implied unit.\n",
    "\n",
    "After, create a Mercury object and print out the value of all its attributes and methods.\n",
    "\n",
    "!!! HELPFUL INFO ABOUT MERCURY !!!\n",
    "Distance from Sun: 58 million\n",
    "Planet Type: Terrestrial\n",
    "Time taken for the planet to orbit the sun: 88 Earth days\n",
    "!!!!!!!!!!!!!!!!!!!!\n",
    "\n",
    "\"\"\"\n",
    "\n",
    "class Mercury(Planet):\n",
    "    def __init__(self, name, distance_from_sun, planet_type):\n",
    "        super().__init__(name, distance_from_sun, planet_type)\n",
    "\n",
    "    # equation to estimate length of a year in Earth days \n",
    "    #days = 365 * sqrt(a^3) where a is the distance_from_sun/distance_to_earth\n",
    "    @staticmethod\n",
    "    def happy_new_year(dist_from_sun):\n",
    "        a = dist_from_sun / 147 #distance from earth to the sun\n",
    "        days = 365 * math.sqrt(a**3)\n",
    "        return {'A year on this planet lasts': days} \n",
    "    \n",
    "\"\"\"\n",
    "C] Design a child class called Jupiter, which inherits from the Planet class.\n",
    "This class should have exactly the same attributes as its parent class, as well as the additional attribute \n",
    "number_of_moons.\n",
    "Your child class should also have a static method called happy_new_year(), which would give us the information on how \n",
    "long a year lasts on the planet (in whatever way you wish!). You can take Earth Days as the implied unit.\n",
    "\n",
    "After, create a Jupiter object and print out the value of all its attributes and methods.\n",
    "\n",
    "\n",
    "!!! HELPFUL INFO ABOUT JUPITER !!!\n",
    "Distance from Sun: 779 million\n",
    "Planet Type: Gas Giant\n",
    "Time taken for the planet to orbit the sun: 4383 Earth days\n",
    "Number of Moons: 80\n",
    "!!!!!!!!!!!!!!!!!!!!\n",
    "\n",
    "\"\"\"\n",
    "\n",
    "class Jupiter(Planet):\n",
    "    def __init__(self, name, distance_from_sun, planet_type, number_of_moons):\n",
    "        super().__init__(name, distance_from_sun, planet_type)\n",
    "        self.number_of_moons = number_of_moons\n",
    "\n",
    "    # equation to calculate length of a year  in Earth days \n",
    "    #days = 365 * sqrt(a^3) where a is the distance_from_sun/distance_to_earth\n",
    "    @staticmethod\n",
    "    def happy_new_year(dist_from_sun):\n",
    "        a = dist_from_sun / 147 #distance from earth to the sun\n",
    "        days = 365 * math.sqrt(a**3)\n",
    "        return {'A year on this planet lasts': days} \n",
    "\n",
    "\n",
    "#Test cases\n",
    "p1 = Planet('Mars', 22, 'Terrestrial')\n",
    "print('from Mars:')\n",
    "print(p1.get_distance_to_earth())\n",
    "\n",
    "m = Mercury('Mercury', 58, 'Terrestrial')\n",
    "print('from Mercury:')\n",
    "print(m.get_distance_to_earth())\n",
    "print(m.happy_new_year(58))\n",
    "\n",
    "j = Jupiter('Jupiter', 779, 'Terrestrial', 80)\n",
    "print('from Jupiter:')\n",
    "print(j.get_distance_to_earth())\n",
    "print(j.happy_new_year(779))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
